### ISSUE TITLE
Training time and hardware 

### ISSUE THREAD

**Issue by pclucas14** [firehose-dataset/congrad#1]
Hi, 

thanks for open sourcing your code. I'm trying to get a run going, however I'm running into memory issues. I'm running the default command in the `Readme`, 
```
bash scripts/train_f10m.sh 256 128 128 0 3 5 --learner MixedReplay --online_buffer_strategy greedy --replay_buffer_strategy stratified --init_weight data/pretrained_weights/stl.pretrained.pt
```

How big of a GPU is needed ? I have a 16Gb one it seems like not enough. Can you also comment on the training time for `Firehose10M` ?

Thanks, 
Lucas

**Comment by hexiang-hu** [comment]
Hi Lucas, 

Sorry for the delay in response, I don't know why GitHub is not notifying me. The training is done using 4 GPU with 12Gb of memory on each of them (RTX2080). It would take about 20+hours to finish the training on Firehose10M.

Also, if you would like to use the preprocessed data for your training, please email me and I could share it with you

Best,
Hexiang

**Comment by hexiang-hu** [comment]
@pclucas14 One thing I forgot to mention in the README is that, to enable multi-GPU training, you would need to set the flag ``--multi_gpu`` to be True.

I updated the README to avoid future confusion.
